# NumPy
**(Numerical python)**
- used for working with arrays.
- In python we have lists that serve the purposr of arrays, but they are slow to process.
- NumPy is incredible libray to perform mathematical and statistical operation due to it's fast and memory efficient as it is optimized to work with letest CPU architectures.
- Numpy aims to provide an array object that is up to 50x faster than traditional Python lists. So proceese can access and manipulate them very effciently.
- Output is row wise

In [63]:
import numpy as np

In [2]:
# Q1: l =[10,5,3,20,30] , for each item in list add 10 --> [20,15,13,30,40]
l =[10,5,3,20,30]
x = []
for i in l:    
    x.append(i+10)
print(x)

[20, 15, 13, 30, 40]


In [3]:
# using array
l =[10,5,3,20,30]

a = np.array(l)
a+10

array([20, 15, 13, 30, 40])

In [4]:
# Q2: l =[10,5,3,20,30,24,25,27,32,37,40,41,42]  ,  --> [40,41,42]
l =[10,5,3,20,30,24,25,27,32,37,40,41,42] 
n = []
for i in l:
    if i>=40:
        n.append(i)
print(n)

[40, 41, 42]


In [5]:
# using array
l =[10,5,3,20,30,24,25,27,32,37,40,41,42] 
a = np.array(l)
a[a>=40]

array([40, 41, 42])

In [6]:
# Q3: l =[10,5,3,20,30,24,25,27,32,37,40,41,42]  , indexnumber --> [0,1,5,7] --- [10,15,27,32]
l =[10,5,3,20,30,24,25,27,32,37,40,41,42]
index = [0,1,5,7]
n = []
for i in index:
    n.append(l[i])
print(n)

[10, 5, 24, 27]


In [7]:
# using array
l =[10,5,3,20,30,24,25,27,32,37,40,41,42] 
a = np.array(l)
a[[0,1,5,7]]

array([10,  5, 24, 27])

In [8]:
#Q4: l1 =[24,25,27,30] , l2 = [32,37,40,41] ---> [56,62,67,71]
l1 =[24,25,27,30]
l2 = [32,37,40,41]

n = []
for i in range(4):
    n.append(l1[i]+l2[i])
print(n)

[56, 62, 67, 71]


In [9]:
# using array
l1 =[24,25,27,30]
l2 = [32,37,40,41]

a = np.array(l1)
b = np.array(l2)
a+b

array([56, 62, 67, 71])

## NumPy array
### 1-D

In [10]:
a = [12,14,16]
print(a)
print(type(a))

[12, 14, 16]
<class 'list'>


In [11]:
a = [12,14,16]
a1 = np.array(a)
print(a1)
print(type(a1))

[12 14 16]
<class 'numpy.ndarray'>


In [9]:
l = 20
a = np.array(l)
print(a)
a.ndim  # for know daimentional
a.shape

20


()

In [13]:
l = [20,3.4,13]
a = np.array(l)
print(a)
a.ndim  # for know daimentional

[20.   3.4 13. ]


1

In [16]:
l = [[3,4],[20,33],[31,4]]
a = np.array(l)
print(a)
a.ndim  # for know daimentional

[[ 3  4]
 [20 33]
 [31  4]]


2

In [2]:
# 0 - D array
a = 45        # same agr [45] rhta to ye 1 D array aata
arr_0 = np.array(a)
print(arr_0)
print(type(arr_0))



45
<class 'numpy.ndarray'>


In [3]:
arr_0.ndim

0

In [4]:
arr_0.shape
# will be emopty tuple

()

In [5]:
a = [11,44,43]
a1 = np.array(a)  # array
print(a1)
print(type(a1))

[11 44 43]
<class 'numpy.ndarray'>


In [6]:
a1.ndim  # for dimention

1

In [7]:
a1.shape # its wil give you num of items in a1 ex - (3,)

(3,)

In [10]:
# convert list to array

l = [10,12,13]
print(l)

a = np.array(l)
print(a)

# what is diffrent bw in array for loop integeted
# To apply automatic for loop that why we are convert list -- array

[10, 12, 13]
[10 12 13]


In [11]:
# convert array to list

a.tolist()

[10, 12, 13]

# Numpy 1D array
- Create a 1D array
- Extract a value(s) from 1D array
- modification within 1D array (Add, replace, delete)

### for creating 1D array
      - convert a list to 1D array -----> np.array(l)
      - function
**functions for creating 1D array**

**arange**

- arange is an array-valued version of the built-in python range function
- **Syntax :** np.arange(start, end , step)

In [13]:
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [31]:
a = np.arange(1,11)
print(a)  # for 1 to 10

[ 1  2  3  4  5  6  7  8  9 10]


**random.randint**

- Return random integers from stat (inclusive) to end (exclusive)
- **Syntax :** np.random.randint(start, end ,num_of_samples)

In [15]:
a = np.random.randint(1,100,10)
print(a)

[27 25 42 27 76 43 28 55 69  1]


In [16]:
# Q. Select any 10 num between 1 to 100 & store them in a list
import random
l = []
for i in range(10):
    l.append(random.randint(1,100))
print(l)
             

[25, 69, 77, 100, 73, 20, 75, 53, 22, 97]


In [19]:
# Q. Select any 10 num between 1 to 100 without any repeation & store them in a list
import random
l = []
for i in range(1000000):
    if i not in l and len(l)<=10:
        l.append(random.randint(1,100))

print(l)

[32, 74, 5, 84, 74, 64, 7, 82, 15, 52, 47]


In [21]:
# Q. Select any 10 even num between 1 to 100 without any repeation & store them in a list
import random
l = []
for i in range(1000000):
    a = random.randint(1,100)
    if a not in l and len(l)<10 and a%2==0:  # if i want only those no who divided by 5 then # a%5==0
        l.append(a)

print(l)

[68, 12, 20, 24, 44, 100, 4, 16, 64, 92]


In [22]:
# ex with while loop of 5
l = []
while True:
    a = random.randint(1,100)
    if a not in l and a%5==0:
        l.append(a)
    if len(l)==10:
        break
print(l)

[50, 55, 15, 95, 90, 25, 100, 35, 5, 80]


**zeros**
- Generate arrays of zeros
- **Syntax :** np.zeros(shape, datatype=)
- by defult its give flot value


In [24]:
a = np.zeros(5)
print(a)
b = np.zeros(5, dtype=int)
print(b)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]


**ones**

- Generate arrays of ones
- **Syntax :** np.ones(shape)

In [27]:
a = np.ones(5, dtype=int)
print(a)

[1 1 1 1 1]


In [29]:
# if i want to create like this 4 4  4 4 or any num then
a = np.zeros(5, dtype=int)+4  # +4 print ..... any value
print(a)

[4 4 4 4 4]


## Accessing elements/ Extracting the values
1. Accessing a single value through indexing
2. Accessing a multipla values based on slicing
3. Accessing a multipla values based on list of index numbers
4. Accessing a multipla values based on condition

In [32]:
a = np.array([9,10,12,4,5,90,6])
print(a)

[ 9 10 12  4  5 90  6]


**1.Accessing a single value through indexing**

In [33]:
#positive indexing
a[3]

np.int64(4)

In [34]:
a[-1]

np.int64(6)

**2.Accessing a multipla values based on slicing**

In [35]:
a[::-2]

array([ 6,  5, 12,  9])

**3.Accessing a multipla values based on indexing**

**Syntax :** array[list od index num]

[]-- list , [[]]---- slicing based on index

In [36]:
# print --- 9,12,4,5,6 
a[[0,2,3,4,6]]   # this are index num    

array([ 9, 12,  4,  5,  6])

**4.Accessing a multipla values based on condition (Mask Indexing or fancy indexing)**
**Syntax :** array[condition]
- fisrt, it will check the condition the item which satisifies the con dition (means which item gives True or the condition), that item will be selected

In [37]:
print(a)

[ 9 10 12  4  5 90  6]


In [38]:
a[a>10]

array([12, 90])

In [41]:
a[(a>10) | (a%2==0)]   # multipal conditions   | or sambly, jb do condition ho to dono ko br me rakho

array([10, 12,  4, 90,  6])

## Modify the values in Numpy
- Add or insert
- Remove or delete
- Replace

**Add a single values in a array**

- Syntax : np.append(array,values)

In [42]:
a = np.array([1,4,5,7,8,9])

a1 = np.append(a,786)
print(a1)

[  1   4   5   7   8   9 786]


**Add a maltipal values in a array**
- Syntax : np.append(array,list of values)

In [43]:
a = np.array([1,4,5,7,8,9])

a2 = np.append(a,[2,6,12,45,76])
print(a2)

[ 1  4  5  7  8  9  2  6 12 45 76]


**Delete a single values in a array**

- Syntax : np.delete(array,index numbers)

In [45]:
a = np.array([1,4,5,7,8,9])

a1 = np.delete(a,3)
print(a1)

[1 4 5 8 9]


**Delete a multipal values in a array**

- Syntax : np.delete(array,[multipal index numbers])

In [46]:
a = np.array([1,4,5,7,8,9])

a1 = np.delete(a,[2,5,1])
print(a1)

[1 7 8]


**Replacing a single value in a 1D array**

In [47]:
a = np.array([1,4,5,7,8,9])

a[1] = 12
print(a)

[ 1 12  5  7  8  9]


**Replacing a multiple value with a single values in a array**

In [49]:
a = np.array([1,4,5,7,8,9])

a[[0,2,4]] = 20
print(a)

[20  4 20  7 20  9]


**Replacing a multiple value with a multiple values in a array**

In [50]:
a = np.array([1,4,5,7,8,9])

a[[1,2,3,5]] = [11,12,13,14]
print(a)

[ 1 11 12 13  8 14]


**Copy array**

In [51]:
a = np.array([1,2,3,4])
b = a.copy()
b[0] = 100
print(a)
print(b)    # b me 1 ---- 100 ho jayega

[1 2 3 4]
[100   2   3   4]


**Sorting an Array**

In [52]:
a = np.array([100,4,6,2,1,10])
print(a)

b = np.sort(a)
print(b)

[100   4   6   2   1  10]
[  1   2   4   6  10 100]


### Operations
**Arthmetic Operations**

In [53]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [54]:
b = np.array([2,3,4,5])
print(b)

[2 3 4 5]


In [55]:
c = a+2
print(c)

[3 4 5 6]


In [56]:
print(a+b)

[3 5 7 9]


In [57]:
print(a**b)

[   1    8   81 1024]


**Comparision operations**

In [73]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,5])
c = np.array([1,2,3,4])

In [74]:
a == b

array([ True,  True,  True, False])

In [75]:
a != b

array([False, False, False,  True])

In [76]:
(a==b) | (a<b)

array([ True,  True,  True,  True])

In [77]:
np.array_equal(a,b)

False

In [78]:
np.array_equal(a,c)

True

**Mathematical operations**

In [79]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [80]:
np.exp(a)  # exponatal e power

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [82]:
np.log(a)  # warning

C:\Users\irfan\AppData\Local\Temp\ipykernel_11032\3068751543.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)  # warning


array([      -inf, 0.        , 0.69314718, 1.09861229])

In [84]:
# warning remove
import warnings
warnings.simplefilter("ignore")

In [85]:
np.log(a) # remove wa

array([      -inf, 0.        , 0.69314718, 1.09861229])