In [1]:
import numpy as np

### 2D - use for datafram 
- two [[ br open is mins its 2d array

# 2D Numpy Array
- convert nested lits to get 2d aaray
- np.zeros,  np.ones, np.eys , np.diag ----- for 2d array

In [2]:
## 1 D array this is 
l = [1,2,3,4]

a = np.array(l)
print(a)

print(a.ndim)
print(a.shape)

[1 2 3 4]
1
(4,)


In [7]:
l = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]  # 2d

a = np.array(l)
print(a)
print(a.ndim)
print(a.shape)
# sep spe rhta h 2d array me aur jbki 1d array me ek me hi rhta hai

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [8]:
l = [[12,13,14],[3,4,5]]
a2 = np.array(l)
print(a2)
print(a2.ndim)
print(a2.shape)

[[12 13 14]
 [ 3  4  5]]
2
(2, 3)


In [9]:
l = [[1,2,3],[4,5,np.nan]]  # np.nan --- its mins no value persent null
a2= np.array(l)
print(a2)
print(a2.ndim)
print(a2.shape)

[[ 1.  2.  3.]
 [ 4.  5. nan]]
2
(2, 3)


In [10]:
 # how to create using fun
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [11]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [12]:
np.zeros((3,3),dtype=int)+5
          

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [13]:
# identity matrix 
np.eye(3,3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [14]:
# diagonal matrix
np.diag([2,8,1])

array([[2, 0, 0],
       [0, 8, 0],
       [0, 0, 1]])

In [16]:
#ex
np.diag([7,8,6,1]) # agr flot ya str me doge to result bhi usi me milega

array([[7, 0, 0, 0],
       [0, 8, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 1]])

In [17]:
# ex 1D array
np.diag([4,5])

array([[4, 0],
       [0, 5]])

In [19]:
# ex 2D array
np.diag([[1,2],[5,9]])

array([1, 9])

In [21]:
# diagonal Matrix
a = np.array([[2,4,6],[5,8,3]])
np.diag(a)   # its give diagonal in form of 1d array

array([2, 8])

## Indxing of 2D array
- to extract  a singal value from 2D array
- Syntax : array_name[row index number, colume index number]

In [22]:
a = np.array([[10,12,33],[23,44,45],[5,6,7],[17,18,19]])
print(a)    # 2d array

[[10 12 33]
 [23 44 45]
 [ 5  6  7]
 [17 18 19]]


In [23]:
a[1,2]

np.int64(45)

In [24]:
a[2,1]  # i want 6

np.int64(6)

**to extract a singal row**

In [34]:
a[0::4] # also this 

array([[10, 12, 33]])

In [35]:
a[0]  #a[1] , a[2], a[3] this way also you can get entrir row

array([10, 12, 33])

**-to extract multipal rows with slicing**

In [39]:
a[0:3]   #a[0:3:2]

array([[10, 12, 33],
       [23, 44, 45],
       [ 5,  6,  7]])

In [48]:
a[1:3 , :]

array([[4, 5, 6],
       [7, 8, 9]])

In [49]:
a[[1,3], :]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [50]:
# all colume
a[ : , 2]

array([ 3,  6,  9, 12, 15, 18, 21])

In [51]:
a[ : , 0:2 ]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11],
       [13, 14],
       [16, 17],
       [19, 20]])

-**to extract multipal slected rows without slicing**
- arrya_name[list of row index numbers]

In [36]:
a[[0,1]]

array([[10, 12, 33],
       [23, 44, 45]])

In [2]:
#ex
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18],[19,20,21]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [3]:
# i want only 0,2,4 index then
a[[0,2,4]]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]])

In [4]:
# also this 
a[[0,1,3,6]]   # agr pattern nhi h to yee kro aur agr hai to scling use kro

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12],
       [19, 20, 21]])

In [5]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

- replace a single value in 2D array

In [16]:
a[3,2]  = 10  #to ab 12 ke jagh 10 hoga 
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 10],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [18]:
a[:,2] # [row , colume]

array([ 3,  6,  9, 10, 15, 18, 21])

In [19]:
a[:,2] = 50
a

array([[ 1,  2, 50],
       [ 4,  5, 50],
       [ 7,  8, 50],
       [10, 11, 50],
       [13, 14, 50],
       [16, 17, 50],
       [19, 20, 50]])

In [22]:
# i want to replce sed row with 20
a[1,:] = 10
a

array([[ 1, 20, 50],
       [10, 10, 10],
       [ 7, 20, 50],
       [10, 20, 50],
       [13, 20, 50],
       [16, 20, 50],
       [19, 20, 50]])

In [24]:
a[1,:] = [11,12,13]  # i want to fill with diff vlaue
a

array([[ 1, 20, 50],
       [11, 12, 13],
       [ 7, 20, 50],
       [10, 20, 50],
       [13, 20, 50],
       [16, 20, 50],
       [19, 20, 50]])

In [25]:
A = np.array([[10,12,33],[93,14,2],[5,6,7],[17,18,19]])
A

array([[10, 12, 33],
       [93, 14,  2],
       [ 5,  6,  7],
       [17, 18, 19]])

In [37]:
# i want to chnge 93,2,5,7
A[[1, 1, 2, 2], [0, 2, 0, 2]]   # row no and then colume number this is simple way to write

array([93,  2,  5,  7])

**Flattening :** Converting 2D array to 1D array. using **.ravel()**

In [40]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])   #  this is 2 D array
print(a)

b = a.ravel()
print("this is 1D array",b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
this is 1D array [0 1 2 3 4 5 6 7 8]


**Reshape array**
    
- Convert a 1D array to 2D array

In [41]:
arr = np.arange(6)
print(arr)
print(arr.shape)

[0 1 2 3 4 5]
(6,)


In [42]:
print(arr.reshape(1,6))

[[0 1 2 3 4 5]]


**2D to 2D**

In [4]:
a=np.array([[0,2,4],[23,1,3]])
print(a)
print(a.shape)

[[ 0  2  4]
 [23  1  3]]
(2, 3)


In [5]:
a.reshape(3,2)

array([[ 0,  2],
       [ 4, 23],
       [ 1,  3]])

In [6]:
a= np.array([[0,1],[10,40],[3,4]])
c = a.reshape(2,3)
print(a)

[[ 0  1]
 [10 40]
 [ 3  4]]


In [9]:
a = np.array([[0,1],[10,40],[3,4]])
c = a.T      # T : transtport 
print(c)

[[ 0 10  3]
 [ 1 40  4]]


**Sort**

In [11]:
# Sorting along an axis: axis = 1 ---> row and axis = 0 --> column

a = np.array([[5,4,6],[2,8,2],[8,9,20]])

b = np.sort(a, axis=0)
print(b)

[[ 2  4  2]
 [ 5  8  6]
 [ 8  9 20]]


**Arthematical Operations**

In [12]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
a+10    # a==10 so all value are 10

array([[11, 12],
       [13, 14],
       [15, 16]])

In [15]:
a>1 # camprition op

array([[False,  True],
       [ True,  True],
       [ True,  True]])

In [17]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[21,4],[67,54],[89,32]])

# ading a & b (elementwise addition)
print(a+b)

[[22  6]
 [70 58]
 [94 38]]


In [19]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[2,4],[6,1],[9,7]])
# array multiplication
# Multiple a * b (elementwise addition)
print(a*b)

[[ 2  8]
 [18  4]
 [45 42]]


In [22]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[2,4],[6,1],[9,7]])

# matrix multiplication
#np.matmul(a,b)

**Join multipal 2D arrays**

In [23]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [24]:
b = np.array([[5,6],[7,8]])
print(b)

[[5 6]
 [7 8]]


In [25]:
# Vertical stack
np.vstack((a,b))     # equal to np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [26]:
# horizontal stack
np.hstack((a,b))       # equal to np.cancatenate((a,b), axis=0

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])